# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='ebook',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to='app_api.Creator'),
            preserve_default=False,
        ),
    ]
